PROJECT_PATH = 'C:\\Users\\leole\\Documents\\RansomRadar'

RAW_ROOT_PATH = f'{PROJECT_PATH}\\dataset\\raw'
HPC_ROOT_path = f'{PROJECT_PATH}\\dataset\\hpcdata'
IRP_ROOT_PATH = f'{PROJECT_PATH}\\dataset\\irplog'
PARSER_PATH = f'{PROJECT_PATH}\\helper\\PARSER\\PARSER\\bin\\Release\\PARSER.exe'
PARSER_PROFILE_PATH = f'{PROJECT_PATH}\\helper\\parse.wpaProfile'
FEATURE_PATH = f'{PROJECT_PATH}\\features'
RESULT_PATH = f'{PROJECT_PATH}\\result'
MODEL_PATH = f'{PROJECT_PATH}\\models'

BACKGROUND_ROOT_PATH = f'{RESULT_PATH}\\background'
BACKGROUND_BASELINE_PATH = f'{BACKGROUND_ROOT_PATH}\\baseline_runs'
BACKGROUND_META_PATH = f'{BACKGROUND_ROOT_PATH}\\meta'
BACKGROUND_PROCESS_SET_PATH = f'{BACKGROUND_META_PATH}\\background_process_union.txt'
